### ISSUE TITLE
Feature: Receive user city or zip, and pull incidents

### ISSUE THREAD

**Issue by acevezl** [acevezl/biker#2]
# User Story:
```
AS A biker
I WANT TO enter my city or zip code
SO THAT I can see incidents near that city or zip code I enterd
```

# Acceptance Criteria:
```
GIVEN an input box 
WHEN I type my city or zip code
THEN an API call to BikeWise returns all incidents within 10 miles of the city and zip code
```
```
GIVEN a call to the BikeWise API
WHEN results are returned
THEN a list of results is displayed in the screen
```

**Comment by anirud314** [comment]
I was able to pull from the api and get the select information we need, I do have a couple questions I would like to go over and I would like to check in before moving on and creating objects out of the data taken from bikewise. The work I have done so far is in the feature/pullIncidents branch

**Comment by anirud314** [comment]
Done, It works the way it should; I added a couple parameters. I first of all added a value limit that I have set to 5 for testing; we can change this later if necessary. I also created a new array to store each searchResult[]; This will be used later when we are trying to store and seperate our individual searches.

**Comment by anirud314** [comment]
Reopening it just in case I missed something; will close if everyone agrees to

**Comment by acevezl** [comment]
Looks good, made a couple updates to the function to incorporate google api
